# Generated by Django 2.2.4 on 2021-04-09 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='jobs_posted_by',
            new_name='job_posted_by',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='jobs_taken_by',
            new_name='job_taken_by',
        ),
    ]
